repo:
- *

pojo:
- src/main/java/com/paywithmyback/labs/githubactions/data/*

repository:
- src/main/java/com/paywithmyback/labs/githubactions/repos/*

test:
- src/test/java/com/paywithmyback/labs/githubactions/*
- src/test/java/com/paywithmyback/labs/githubactions/**/*

resource:
- src/main/resources/**/*

