spring:
  datasource:
    url: jdbc:h2:mem:worlds
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

management:
  info:
    env:
      enabled: true
    java:
      enabled: false
  endpoints:
    web:
      base-path: /
      path-mapping:
        startup: probe/startup
        info: version
        health: probe
        httptrace: trace
      exposure:
        include: health,info,startup,httptrace
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    trace:
      enabled: ${MANAGEMENT_ENDPOINT_TRACE_ENABLED:false}

