name: Add Size Label to PR

on:
  pull_request

jobs:
  build:
    name: Add Size Label to PR
    runs-on: ubuntu-18.04
    steps:
      - name: Add Size Label to PR
        uses: WizardOhio24/label-pr-size-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
