name: 'Check Title Lint for PR'
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@2.0.0
        with:
          regex: '(?:\s|^)([A-Z]+-[0-9]+)(?=\s|$)'